project_id = "mmemme"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]

[db]
port = 54322
major_version = 15

[auth]
enabled = true
site_url = "mmemme://auth"

[functions.initialize-payment]
verify_jwt = true

[functions.paystack-webhook]
verify_jwt = false
