import NetInfo from "@react-native-community/netinfo";
import { Ionicons } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";
import { router, useLocalSearchParams } from "expo-router";
import { useEffect, useState } from "react";
import { ActivityIndicator, FlatList, Image, Pressable, RefreshControl, SafeAreaView, StyleSheet, Text, TextInput, View } from "react-native";
import { colors, Eyebrow, PrimaryButton, TrustBadge } from "../src/components/ui";
import { useAuth } from "../src/lib/auth";
import { isSupabaseConfigured } from "../src/lib/supabase";
import { listVendors, type Vendor } from "../src/lib/vendors";

const formatNaira = (kobo: number | null) => kobo == null ? "Request pricing" : `From ₦${Math.round(kobo/100).toLocaleString("en-NG")}`;
export default function HomeScreen() {
  const { brief } = useLocalSearchParams<{ brief?: string }>(); const { user } = useAuth();
  const [vendors,setVendors]=useState<Vendor[]>([]); const [category,setCategory]=useState<"venue"|"caterer"|undefined>(); const [area,setArea]=useState("");
  const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false); const [error,setError]=useState(""); const [offline,setOffline]=useState(false);
  const load=async(showRefresh=false)=>{showRefresh?setRefreshing(true):setLoading(true);setError("");try{setVendors(await listVendors({category,area:area.trim()||undefined}));}catch(error){setError(error instanceof Error?error.message:"We could not load vendors.");}finally{setLoading(false);setRefreshing(false);}};
  useEffect(()=>{load();},[category]);
  useEffect(()=>NetInfo.addEventListener((state)=>setOffline(state.isConnected===false)),[]);
  return <SafeAreaView style={styles.safe}><FlatList data={vendors} keyExtractor={(item)=>item.id} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>load(true)} tintColor={colors.plum}/>} ListHeaderComponent={<>
    <View style={styles.nav}><Text style={styles.wordmark}>mmemme</Text><Pressable accessibilityRole="button" accessibilityLabel={user?"Open account":"Sign in"} onPress={()=>router.push(user?"/profile":{pathname:"/auth",params:{next:"/profile",intent:"view your account"}})} style={styles.account}><Ionicons name={user?"person":"person-outline"} size={23} color={colors.ink}/></Pressable></View>
    {brief==="saved"&&<View style={styles.saved}><Ionicons name="checkmark-circle" size={20} color={colors.success}/><Text style={styles.savedText}>Your wedding brief is saved.</Text></View>}
    {offline&&<View style={styles.offline}><Ionicons name="cloud-offline-outline" size={19} color="#68470D"/><Text style={styles.offlineText}>You’re offline. Showing the last loaded screen.</Text></View>}
    <LinearGradient colors={["#F9E4E7","#FFF4E6"]} style={styles.hero}><Eyebrow>Your wedding, held with care</Eyebrow><Text style={styles.title}>Book the people who bring it all together.</Text><Text style={styles.subtitle}>Curated Lagos venues and caterers. Clear packages, confirmed dates and safer deposits.</Text><PrimaryButton accessibilityLabel="Create your wedding brief" onPress={()=>router.push("/brief")}>Create my wedding brief</PrimaryButton></LinearGradient>
    <View style={styles.sectionTitle}><View><Eyebrow>Handpicked in Lagos</Eyebrow><Text style={styles.heading}>A shorter, better list</Text></View><Text style={styles.count}>{vendors.length} found</Text></View>
    <View style={styles.filters}><View style={styles.chips}>{([undefined,"venue","caterer"] as const).map((item)=><Pressable key={item??"all"} accessibilityRole="button" accessibilityState={{selected:category===item}} onPress={()=>setCategory(item)} style={[styles.chip,category===item&&styles.chipActive]}><Text style={[styles.chipText,category===item&&styles.chipTextActive]}>{item?`${item[0].toUpperCase()}${item.slice(1)}s`:"All"}</Text></Pressable>)}</View><View style={styles.search}><Ionicons name="location-outline" size={20} color={colors.muted}/><TextInput accessibilityLabel="Filter by Lagos area" onChangeText={setArea} onSubmitEditing={()=>load()} placeholder="Filter by Lagos area" placeholderTextColor="#887580" returnKeyType="search" style={styles.searchInput} value={area}/><Pressable accessibilityRole="button" accessibilityLabel="Apply area filter" onPress={()=>load()}><Ionicons name="arrow-forward-circle" size={27} color={colors.plum}/></Pressable></View></View>
  </>}
  ListEmptyComponent={loading?<View style={styles.state}><ActivityIndicator accessibilityLabel="Loading vendors" color={colors.plum}/><Text style={styles.stateText}>Finding verified vendors…</Text></View>:error?<View style={styles.state}><Ionicons name="alert-circle-outline" size={30} color={colors.coral}/><Text accessibilityRole="alert" style={styles.stateTitle}>We could not load the marketplace.</Text><Text style={styles.stateText}>{error}</Text>{isSupabaseConfigured&&<PrimaryButton onPress={()=>load()}>Try again</PrimaryButton>}</View>:<View style={styles.state}><Ionicons name="search-outline" size={31} color={colors.plum}/><Text style={styles.stateTitle}>No exact matches yet.</Text><Text style={styles.stateText}>Try another area or category. We never pad results with unverified vendors.</Text><PrimaryButton onPress={()=>{setArea("");setCategory(undefined);}}>Clear filters</PrimaryButton></View>}
  renderItem={({item,index})=><Pressable accessibilityRole="button" accessibilityLabel={`View ${item.name}, ${item.category}`} onPress={()=>router.push({pathname:"/vendor/[id]",params:{id:item.id}})} style={styles.card}>{item.heroUrl?<Image accessibilityLabel={`${item.name} portfolio image`} source={{uri:item.heroUrl}} style={styles.image}/>:<View style={[styles.image,{backgroundColor:index%2?"#C5A66A":"#D7B8A5"}]}><Text style={styles.imageLetter}>{item.name.slice(0,1)}</Text></View>}<View style={styles.category}><Text style={styles.categoryText}>{item.category}</Text></View><View style={styles.cardBody}><TrustBadge/><Text style={styles.cardTitle}>{item.name}</Text><Text style={styles.meta}>{item.area}{item.capacity_max?` · up to ${item.capacity_max} guests`:""}</Text><Text style={styles.price}>{formatNaira(item.price_from_kobo)}</Text></View></Pressable>}
  ListFooterComponent={!loading&&!error&&vendors.length?<View style={styles.promise}><Ionicons name="shield-checkmark-outline" size={28} color={colors.plum}/><View style={{flex:1}}><Text style={styles.promiseTitle}>Verified means something here.</Text><Text style={styles.promiseText}>We show exactly what MMEMME checked, when it was checked and what verification does not guarantee.</Text></View></View>:null}/></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.ivory},content:{padding:18,paddingBottom:48},nav:{height:62,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},wordmark:{color:colors.plum,fontSize:26,fontWeight:"900",letterSpacing:-1},account:{width:44,height:44,borderRadius:22,borderWidth:1,borderColor:colors.border,alignItems:"center",justifyContent:"center"},saved:{flexDirection:"row",alignItems:"center",gap:8,backgroundColor:"#E6F4EE",padding:12,borderRadius:14,marginBottom:12},savedText:{color:colors.success,fontWeight:"800"},offline:{flexDirection:"row",gap:9,backgroundColor:"#FFF2D5",padding:12,borderRadius:14,marginBottom:12},offlineText:{color:"#68470D",fontWeight:"700"},hero:{borderRadius:30,padding:24,gap:16,overflow:"hidden"},title:{color:colors.ink,fontSize:38,lineHeight:41,letterSpacing:-1.4,fontWeight:"800"},subtitle:{color:colors.muted,fontSize:16,lineHeight:24},sectionTitle:{flexDirection:"row",justifyContent:"space-between",alignItems:"flex-end",marginTop:34,marginBottom:16},heading:{fontSize:27,color:colors.ink,fontWeight:"800",marginTop:5},count:{color:colors.muted,fontSize:12},filters:{gap:12,marginBottom:16},chips:{flexDirection:"row",gap:8},chip:{minHeight:43,paddingHorizontal:17,borderRadius:999,borderWidth:1,borderColor:colors.border,justifyContent:"center",backgroundColor:colors.white},chipActive:{backgroundColor:colors.plum,borderColor:colors.plum},chipText:{color:colors.ink,fontWeight:"800"},chipTextActive:{color:colors.white},search:{minHeight:54,flexDirection:"row",alignItems:"center",gap:8,borderWidth:1,borderColor:colors.border,backgroundColor:colors.white,borderRadius:17,paddingHorizontal:14},searchInput:{flex:1,color:colors.ink,fontSize:16},card:{backgroundColor:colors.white,borderRadius:24,marginBottom:18,borderWidth:1,borderColor:colors.border,overflow:"hidden"},image:{height:178,width:"100%",alignItems:"center",justifyContent:"center"},imageLetter:{color:"rgba(255,255,255,.72)",fontSize:78,fontWeight:"900"},category:{position:"absolute",right:12,top:12,borderRadius:999,backgroundColor:"rgba(50,21,39,.84)",paddingHorizontal:12,paddingVertical:7},categoryText:{color:colors.white,textTransform:"capitalize",fontWeight:"700",fontSize:12},cardBody:{padding:17,gap:8},cardTitle:{color:colors.ink,fontSize:23,fontWeight:"800"},meta:{color:colors.muted,lineHeight:20},price:{color:colors.plum,fontSize:16,fontWeight:"900"},state:{padding:30,alignItems:"center",gap:13},stateTitle:{fontSize:19,fontWeight:"900",color:colors.ink,textAlign:"center"},stateText:{color:colors.muted,textAlign:"center",lineHeight:20},promise:{flexDirection:"row",gap:14,marginTop:10,padding:20,backgroundColor:colors.rose,borderRadius:22},promiseTitle:{color:colors.ink,fontWeight:"900",fontSize:17,marginBottom:5},promiseText:{color:colors.muted,lineHeight:20}});
